-- Model: addons/planning/DRIVER_BASIS.md
--
-- ★★★ THE HAND-WRITTEN FIXTURE LIST (A11.1a, P2).
--
-- A11.1a, Q1 accepted: *"build to the shape; the flattener arrives with a consumer to
-- satisfy — V1 is graded against a HAND-WRITTEN fixture list in that shape."*
--
-- ⚠⚠ HAND-WRITTEN IS THE POINT, not a shortcut. Fixtures generated by the flattener
-- would assert that the flattener does what the flattener does — the same fault the
-- A1.2 invariant table names in `smoke_dungeonrunroutes`: *"values copied out of the
-- new code would assert that the new code does what the new code does."* These records
-- were typed from `driver_data_model.md` §A1 and `contract.lua`, and the producer will
-- be graded AGAINST them rather than the other way round.
--
-- ★ Every case below exists because a RULE says it can happen. None is decoration.

local F = {}

-- ═════════════════════════════════════════════════════════════════════════════
-- CHARACTERISTIC records — one per node.
-- address: mapID · rid · bid · cid   then   stage · step · posX,posY,posZ · r ·
--          band · nextType · nextArg · trigger
-- ═════════════════════════════════════════════════════════════════════════════
F.characteristic = {

    -- 1 · AN ORDINARY BEACON. ⚠ `cid` ABSENT - a beacon carries a reach and a stage of
    -- its own (G2, §299), so the address stops at BID. Step is 0: a beacon has no
    -- ordinal, and 0 is the value for "no gate" rather than a blank slot (§385c).
    { mapID = 33, rid = 7, bid = 1, cid = nil,
      stage = 1, step = 0,
      posX = -231.44, posY = 1502.08, posZ = 88.32,
      r = 8, band = 2.5,
      nextType = "step", nextArg = nil, trigger = nil },

    -- 2 · A CHILD of that beacon, in the ordinal line at 1.
    { mapID = 33, rid = 7, bid = 1, cid = 1,
      stage = 1, step = 1,
      posX = -228.10, posY = 1499.63, posZ = 88.30,
      r = 4, band = 2.5,
      nextType = "step", nextArg = nil, trigger = nil },

    -- 3 · AN UN-ORDINALLED CHILD - the UPDATE type. §311: *"children who are NOT in the
    -- ordinal are still listened to"*, `child.ordinal = nil` in the store, **0 on the
    -- record**. ⚠ This is the case that makes 0-not-blank load-bearing: an empty slot
    -- would be indistinguishable from a truncated line.
    { mapID = 33, rid = 7, bid = 1, cid = 2,
      stage = 1, step = 0,
      posX = -240.00, posY = 1510.00, posZ = 88.10,
      r = 12, band = 2.5,
      nextType = "step", nextArg = nil, trigger = nil },

    -- 4 · A STAGELESS RECOVERY BEACON. stage 0 = *"permission to read it"* - always
    -- eligible, outside the ordered run. ⚠ A2.10a: it must NOT promote the index, and
    -- A2.10c: it has NO `stage:ordinal` path, so the driver finds it by address.
    { mapID = 33, rid = 7, bid = 2, cid = nil,
      stage = 0, step = 0,
      posX = -180.75, posY = 1440.20, posZ = 84.00,
      r = 20, band = 2.5,
      nextType = "step", nextArg = nil, trigger = nil },

    -- 5 · A `Set(N)` NODE - `Next` is ONE field in TWO slots (RI-18 Q3), and `nextArg`
    -- is present ONLY here. ⚠ The other four emit the slot EMPTY rather than omitting
    -- it, so positions never shift.
    { mapID = 33, rid = 7, bid = 3, cid = nil,
      stage = 4, step = 0,
      posX = -95.10, posY = 1388.44, posZ = 91.75,
      r = 10, band = 2.5,
      nextType = "set", nextArg = 6, trigger = nil },

    -- 6 · A SECOND ROUTE ON THE SAME MAP, to prove `rid` gates. ⚠ Its `bid` is 1 -
    -- the same number as record 1 - which is legal and is exactly why the ADDRESS is
    -- the whole key rather than the BID alone.
    { mapID = 33, rid = 8, bid = 1, cid = nil,
      stage = 1, step = 0,
      posX = 402.00, posY = 900.50, posZ = 12.25,
      r = 6, band = 2.5,
      nextType = "step", nextArg = nil, trigger = nil },
}

-- ═════════════════════════════════════════════════════════════════════════════
-- BEHAVIOUR records — N per node, one per action tab. §A1.1.
-- address then sense · action · arg
-- ⚠ `arg` is an ID REFERENCE. Record 3 below carries `arg = 1` and that ONE is an
-- index into the shipped names table, NOT a boss called "1". A11.1c goes red the day
-- a label is put back into a payload, and this is the field it would come back in.
-- ═════════════════════════════════════════════════════════════════════════════
F.behaviour = {

    -- the ordinary beacon: arrive, and that is all
    { mapID = 33, rid = 7, bid = 1, cid = nil,
      sense = "whenOn", action = "supertrack", arg = nil },

    -- the child in the line: two tabs on ONE node. A2.7 - a step completes when ALL
    -- its action tabs complete, which is why more than one exists here at all.
    { mapID = 33, rid = 7, bid = 1, cid = 1,
      sense = "whenOn", action = "note", arg = 4 },
    { mapID = 33, rid = 7, bid = 1, cid = 1,
      sense = "whenOff", action = "say", arg = 5 },

    -- the boss node: the row IS the declaration `<sense>:<action>:<arg>` (RI-17)
    { mapID = 33, rid = 7, bid = 3, cid = nil,
      sense = "seen", action = "boss", arg = 1 },

    -- the update child, listened to at any time
    { mapID = 33, rid = 7, bid = 1, cid = 2,
      sense = "whenOn", action = "note", arg = 6 },

    -- ⚠ THE STAGELESS BEACON HAS A TAB TOO. A recovery node that senses nothing is a
    -- node that can never complete, so "always eligible" would mean "always waiting".
    { mapID = 33, rid = 7, bid = 2, cid = nil,
      sense = "whenOn", action = "supertrack", arg = nil },

    -- the second route
    { mapID = 33, rid = 8, bid = 1, cid = nil,
      sense = "whenOn", action = "note", arg = 7 },
}

-- ★ THE VOCABULARIES the id-typed fields draw from. Declared HERE rather than imported
-- from `routes.lua`, deliberately: A11.1b forbids the driver reaching for `Routes.*`,
-- and a fixture list that imported it would make the grader depend on the thing being
-- graded. ⚠ If these drift from `Routes.SENSE_WORDS` / `ROW_ACTIONS`, the smoke says
-- so rather than silently grading against a private copy.
F.vocabulary = {
    sense    = { whenOn = true, seen = true, whenOff = true },
    action   = { boss = true, note = true, supertrack = true, say = true },
    nextType = { step = true, stage = true, set = true },
}

return F
