-- Deutsch (deDE)
local L = {
    ["MINIMAP_OPEN_HUB"] = "Hub öffnen",
    ["MINIMAP_DISPLAY"] = "Einstellungen",
    ["MINIMAP_LANGUAGE"] = "Sprache",
    ["MINIMAP_HIDE"] = "Minikarten-Button ausblenden",
    ["MINIMAP_TIP_LEFT"] = "Linksklick: Hub öffnen",
    ["MINIMAP_TIP_RIGHT"] = "Rechtsklick: Menü",
    ["MINIMAP_TIP_DRAG"] = "Ziehen: Symbol verschieben",

    ["LANGUAGE_TITLE"] = "Libellus Leti Sprache",
    ["LANGUAGE_DESC"] = "Wähle die Sprache für Menüs und Optionen von Libellus Leti. Zauber- und Talentnamen bleiben wie bei Ascension.",
    ["LANGUAGE_SECTION"] = "Sprache",
    ["LANGUAGE_APPLIED"] = "Sprache aktualisiert.",

    ["DISPLAY_TITLE"] = "Libellus Leti Einstellungen",
    ["DISPLAY_DESC"] = "Stance-Hinweise, HUD-Balken, Namensplaketten und Darstellung.",
    ["SETTINGS_TAB_STANCE"] = "Stance-Hinweise",
    ["SETTINGS_TAB_DISPLAY"] = "Anzeige",
    ["SETTINGS_TAB_NAMEPLATES"] = "Namensplaketten",
    ["SETTINGS_TAB_APPEARANCE"] = "Darstellung",
    ["SETTINGS_STANCE_TIP"] = "Wähle, wo Undead-Stance-Hinweise erscheinen dürfen.",
    ["SETTINGS_NAMEPLATES_TIP"] = "Lebens-/Ressourcen-/Zauberbalken auf Ascension-Namensplaketten ausblenden, Namen behalten.",
    ["SECTION_WHERE"] = "Wo",
    ["SECTION_DISPLAY"] = "Anzeige",
    ["SECTION_BAR_TEXTURE"] = "Balkentextur",
    ["SECTION_MINION_HP_BAR"] = "Diener-Textur",
    ["SECTION_FONT"] = "Schriftart",
    ["SECTION_FONT_SIZE"] = "Schriftgröße",
    ["SECTION_LAYOUT"] = "Layout",

    ["WHERE_ALL"] = "Überall",
    ["WHERE_WORLD"] = "Offene Welt",
    ["WHERE_RAID"] = "Schlachtzüge",
    ["WHERE_DUNGEON"] = "Dungeons",
    ["WHERE_ARENA"] = "Arena",
    ["WHERE_BATTLEGROUND"] = "Schlachtfelder",

    ["OPT_SHOW_MANA"] = "Manazahlen anzeigen",
    ["OPT_SHOW_HEALTH"] = "Lebenszahlen anzeigen",
    ["OPT_SHOW_REGEN_RATE"] = "Letzte Mana-Zahl beschriften",
    ["OPT_REGEN_ONLY"] = "Nur Regeneration",
    ["OPT_SHOW_MANA_BAR"] = "Mana-Bogen anzeigen",
    ["OPT_SHOW_HEALTH_BAR"] = "Lebens-Bogen anzeigen",
    ["OPT_SHOW_RUNIC_BAR"] = "Runenmacht-Bogen anzeigen",
    ["OPT_SHOW_ANIMATE_BAR"] = "Animate-Leiste anzeigen",
    ["OPT_CONSOLIDATE_BUFFS"] = "Doppelte Buffs stapeln",
    ["OPT_SHOW_PROC_BAR"] = "Proc-Leiste anzeigen",
    ["OPT_SHOW_ZOMBIE"] = "Zombie-Zähler anzeigen",
    ["OPT_SHOW_MINION_HP"] = "Diener-LP-Balken anzeigen",
    ["SECTION_NAMEPLATES"] = "Namensplaketten (nur Namen)",
    ["PLATE_ALL"] = "Alle",
    ["PLATE_GUARDIANS"] = "Wächter",
    ["PLATE_PLAYERS"] = "Spieler",
    ["PLATE_NPCS"] = "NSCs",
    ["PLATE_ENEMIES"] = "Feinde",
    ["OPT_HIDE_FRIENDLY_PLATES"] = "Freundliche Namensplaketten ausblenden",
    ["OPT_SHOW_MINIMAP"] = "Minikarten-Button anzeigen",
    ["OPT_MINION_TOOLTIPS"] = "Diener-DPS in Zaubertooltips",

    ["BTN_SHOW"] = "Anzeigen",
    ["BTN_HIDE"] = "Ausblenden",
    ["BTN_TEST_PREVIEW"] = "Vorschau testen",
    ["BTN_RESET_BARS"] = "Balken zurücksetzen",

    ["HUB_TAB_COMBAT"] = "Kampf",
    ["HUB_TAB_COMBAT_SUB"] = "Armee · LF · DPS",
    ["HUB_TAB_COMBAT_TIP"] = "Armee, Lebensenergie, DPS und ST gegen AoE",
    ["HUB_TAB_MINIONS"] = "Diener",
    ["HUB_TAB_MINIONS_SUB"] = "Wächterblatt",
    ["HUB_TAB_MINIONS_TIP"] = "Live-Wächterblatt — Werte und Modell",
    ["HUB_TAB_GUIDES"] = "Ratgeber",
    ["HUB_TAB_GUIDES_SUB"] = "Werte · Papier · Buffs",
    ["HUB_TAB_GUIDES_TIP"] = "Wertgrenzen, Papier-DPS und Buff-Empfehlungen",
    ["HUB_TAB_SETUP"] = "Einstellung",
    ["HUB_TAB_SETUP_SUB"] = "Balken · Einstellungen",
    ["HUB_TAB_SETUP_TIP"] = "Einstellungen öffnen (Stance, Balken, Namensplaketten, Schriften, Layout)",
    ["HUB_TAB_CREDITS"] = "Credits",
    ["HUB_TAB_CREDITS_SUB"] = "Danke",
    ["HUB_TAB_CREDITS_TIP"] = "Danke an alle, die Libellus Leti geholfen haben",
    ["HUB_CREDITS_TITLE"] = "Danke",
    ["WIZARD_WELCOME_TITLE"] = "Willkommen bei Libellus Leti",
    ["WIZARD_TITLE"] = "Was mochtest du von Leti?",
    ["WIZARD_SKIP"] = "Einstellungen behalten",
    ["WIZARD_CONTINUE"] = "Einrichtung fortsetzen",
    ["WIZARD_BACK"] = "Zuruck",
    ["WIZARD_NEXT"] = "Weiter",
    ["WIZARD_FINISH"] = "Fertig",
    ["WIZARD_DONE"] = "Fertig",

    ["LOADED"] = "v%s geladen. Tippe /leti zum Öffnen.",
    ["HELP_WELCOME"] = "Zum ersten Mal hier? Ein Willkommensfenster fragt, was du von Leti mochtest — oder tippe /leti welcome.",
}

Mancer.LocaleModule.Register("deDE", L)
