-- English (default) — full UI coverage for menus / Display / Language / Hub tabs.
local L = {
    -- Minimap
    ["MINIMAP_OPEN_HUB"] = "Open Hub",
    ["MINIMAP_DISPLAY"] = "Settings",
    ["MINIMAP_LANGUAGE"] = "Language",
    ["MINIMAP_HIDE"] = "Hide minimap button",
    ["MINIMAP_TIP_LEFT"] = "Left-click: Open Hub",
    ["MINIMAP_TIP_RIGHT"] = "Right-click: Menu",
    ["MINIMAP_TIP_DRAG"] = "Drag: Move icon",

    -- Language page
    ["LANGUAGE_TITLE"] = "Libellus Leti Language",
    ["LANGUAGE_DESC"] = "Choose the language for Libellus Leti menus and options. Spell and talent names stay as Ascension shows them.",
    ["LANGUAGE_SECTION"] = "Language",
    ["LANGUAGE_APPLIED"] = "Language updated.",

    -- Display / Settings page
    ["DISPLAY_TITLE"] = "Libellus Leti Settings",
    ["DISPLAY_DESC"] = "Stance prompts, HUD bars, nameplates, and appearance.",
    ["SETTINGS_TAB_STANCE"] = "Stance Prompts",
    ["SETTINGS_TAB_DISPLAY"] = "Display",
    ["SETTINGS_TAB_NAMEPLATES"] = "Nameplates",
    ["SETTINGS_TAB_APPEARANCE"] = "Appearance",
    ["SETTINGS_TAB_SHARE"] = "Share",
    ["INSPECT_TREE_BUTTON"] = "Show Talent Tree",
    ["INSPECT_TREE_TIP"] = "Opens Class + Animation/Death/Rime with their inspected picks.",
    ["INSPECT_TREE_TITLE"] = "Inspect Talent Tree",
    ["INSPECT_TREE_NOTE"] = "Colour = taken · Greyscale = not taken · Side passives hidden",
    ["INSPECT_TREE_RANK"] = "Inspect rank: %d / %d",
    ["INSPECT_TREE_CLASS"] = "NECROMANCER",
    ["INSPECT_TREE_SPEC"] = "ANIMATION",
    ["INSPECT_TREE_BANNER"] = "Inspect build · %s · Spec %s · %s",
    ["INSPECT_TREE_STATUS"] = "%s · Spec %s · %d talents taken",
    ["INSPECT_TREE_UNTAKEN"] = "Not taken on this inspect build",
    ["INSPECT_TREE_NO_UNIT"] = "Inspect a Necromancer first.",
    ["INSPECT_TREE_NOT_NECRO"] = "Inspect talent tree is Necromancer-only for now.",
    ["INSPECT_TREE_NO_API"] = "Character Advancement inspect API missing.",
    ["INSPECT_TREE_EMPTY"] = "No inspect build data yet — open Build tab, pick a specialization, try again.",
    ["INSPECT_TREE_OPENED_COA"] = "Showing %s Spec %d (%s · %d talents).",
    ["SETTINGS_STANCE_TIP"] = "Choose where Undead stance prompts are allowed to appear.",
    ["SETTINGS_NAMEPLATES_TIP"] = "Hide health/power/cast bars on Ascension nameplates but keep the floating name text.",
    ["OPT_MUTE_PLATES_CAPITALS"] = "Mute nameplates in capital cities",
    ["SECTION_WHERE"] = "Where",
    ["SECTION_DISPLAY"] = "Display",
    ["SECTION_BAR_TEXTURE"] = "Bar texture",
    ["SECTION_MINION_HP_BAR"] = "Minion Texture",
    ["SECTION_FONT"] = "Font",
    ["SECTION_FONT_SIZE"] = "Font size",
    ["SECTION_LAYOUT"] = "Layout",

    ["WHERE_ALL"] = "All",
    ["WHERE_WORLD"] = "Open world",
    ["WHERE_RAID"] = "Raids",
    ["WHERE_DUNGEON"] = "Dungeons",
    ["WHERE_ARENA"] = "Arena",
    ["WHERE_BATTLEGROUND"] = "Battlegrounds",

    ["OPT_SHOW_MANA"] = "Show mana ticks",
    ["OPT_SHOW_HEALTH"] = "Show health ticks",
    ["OPT_SHOW_REGEN_RATE"] = "Show last mana tick label",
    ["OPT_REGEN_ONLY"] = "Regen-only filter",
    ["OPT_SHOW_MANA_BAR"] = "Show mana arc bar",
    ["OPT_SHOW_HEALTH_BAR"] = "Show health arc bar",
    ["OPT_SHOW_RUNIC_BAR"] = "Show runic power bar",
    ["OPT_SHOW_ANIMATE_BAR"] = "Show Animate bar",
    ["OPT_CONSOLIDATE_BUFFS"] = "Stack duplicate buffs",
    ["OPT_SHOW_PROC_BAR"] = "Show proc bar",
    ["OPT_SHOW_ZOMBIE"] = "Show zombie counter",
    ["OPT_SHOW_LIFE_FORCE"] = "Show Life Force count",
    ["OPT_SHOW_MINION_HP"] = "Show minion HP bars",
    ["SECTION_NAMEPLATES"] = "Nameplates (names only)",
    ["PLATE_ALL"] = "All",
    ["PLATE_GUARDIANS"] = "Guardians",
    ["PLATE_PLAYERS"] = "Players",
    ["PLATE_NPCS"] = "NPCs",
    ["PLATE_ENEMIES"] = "Enemies",
    ["OPT_HIDE_FRIENDLY_PLATES"] = "Hide friendly plates",
    ["OPT_SHOW_MINIMAP"] = "Show minimap button",
    ["OPT_MINION_TOOLTIPS"] = "Minion DPS spell tooltips",

    ["BTN_SHOW"] = "Show",
    ["BTN_HIDE"] = "Hide",
    ["BTN_TEST_PREVIEW"] = "Test Preview",
    ["BTN_RESET_BARS"] = "Reset Bars",
    ["BTN_SHARE_LAYOUT"] = "Share Layout",

    ["LAYOUT_SHARE_TITLE"] = "Share Layout",
    ["LAYOUT_SHARE_DESC"] = "Copy your compact layout code to share, or paste someone else's code below. Codes start with !Leti:1! (positions) or !Leti:2! (full look).",
    ["LAYOUT_SHARE_EXPORT"] = "Your layout code",
    ["LAYOUT_SHARE_INCLUDE_LOOK"] = "Include fonts, textures & colors (!Leti:2!)",
    ["LAYOUT_SHARE_COPY"] = "Copy Code",
    ["LAYOUT_SHARE_IMPORT"] = "Paste layout code",
    ["LAYOUT_SHARE_APPLY"] = "Apply Layout",
    ["LAYOUT_SHARE_CLOSE"] = "Close",
    ["LAYOUT_SHARE_BACK"] = "Back",
    ["LAYOUT_SHARE_COPIED"] = "Layout code copied — paste it in Discord or chat.",
    ["LAYOUT_SHARE_SELECT"] = "Select the code above and press Ctrl+C.",
    ["LAYOUT_SHARE_APPLIED"] = "Layout applied.",
    ["LAYOUT_SHARE_FAILED"] = "Could not import layout.",
    ["LAYOUT_SHARE_EMPTY"] = "Nothing to copy yet.",

    -- Hub tabs
    ["HUB_TAB_COMBAT"] = "Combat",
    ["HUB_TAB_COMBAT_SUB"] = "Army · LF · DPS",
    ["HUB_TAB_COMBAT_TIP"] = "Army picks, Life Force, DPS, and ST vs AoE",
    ["HUB_TAB_MINIONS"] = "Minions",
    ["HUB_TAB_MINIONS_SUB"] = "Guardian sheet",
    ["HUB_TAB_MINIONS_TIP"] = "Live guardian sheet — stats and model",
    ["HUB_TAB_GUIDES"] = "Guides",
    ["HUB_TAB_GUIDES_SUB"] = "Stats · Paper · Buffs",
    ["HUB_TAB_GUIDES_TIP"] = "Stat caps, paper DPS, and buff picks",
    ["HUB_TAB_SETUP"] = "Setup",
    ["HUB_TAB_SETUP_SUB"] = "Bars · Settings",
    ["HUB_TAB_SETUP_TIP"] = "Open settings (stance prompts, bars, nameplates, fonts, layout)",
    ["HUB_TAB_CREDITS"] = "Credits",
    ["HUB_TAB_CREDITS_SUB"] = "Thanks",
    ["HUB_TAB_CREDITS_TIP"] = "Thanks to everyone who helped with Libellus Leti",

    ["HUB_CREDITS_TITLE"] = "Thanks",
    ["HUB_CREDITS_BODY"] = table.concat({
        "Libellus Leti is built for casual Animation Necromancers on Ascension.",
        "",
        "Huge thanks to everyone who tested builds, shared feedback, and helped dig through talent / UI files so the Hub, tooltips, and minion tools could ship.",
        "",
        "Author: Mortuus (Discord: LtGenZombie)",
        "If this addon helped your necro, share it with another undead friend.",
        "",
        "Tip: /leti welcome opens the setup wizard anytime.",
    }, "\n"),

    ["WIZARD_WELCOME_TITLE"] = "Welcome to Libellus Leti",
    ["WIZARD_TITLE"] = "What do you want from Leti?",
    ["WIZARD_WARN_BODY"] = table.concat({
        "Looks like this character already has Leti set up.",
        "",
        "You can still walk through and pick what to turn on — just know it may change what you have now.",
        "Or skip and leave everything as-is.",
    }, "\n"),
    ["WIZARD_SKIP"] = "Skip for now",
    ["WIZARD_CONTINUE"] = "Continue setup",
    ["WIZARD_BACK"] = "Back",
    ["WIZARD_NEXT"] = "Next",
    ["WIZARD_FINISH"] = "Finish",
    ["WIZARD_STEP"] = "%d / %d",
    ["WIZARD_SKIP_QUIZ"] = "Skip for now",
    ["WIZARD_OPEN_SETUP"] = "Open Setup",
    ["WIZARD_DONE"] = "Done",
    ["WIZARD_SUMMARY_TITLE"] = "You're good to go",
    ["WIZARD_SUMMARY_INTRO"] = "Here's what you turned on:",
    ["WIZARD_SUMMARY_TIP"] = "Change your mind later anytime in Setup.",
    ["WIZARD_SUMMARY_NONE"] = "Nothing got turned on — that's fine. Pop into Setup when you're ready, or run /leti welcome again.",
    ["WIZARD_SKIPPED"] = "Left your settings alone. Run /leti welcome anytime if you want another pass.",
    ["WIZARD_OPT_BARS"] = "Arc bars",
    ["WIZARD_BLURB_BARS"] = "Those curved mana and health vines around your character. Tick one to try it on — you can drag and resize while you're here. Hit Next when it feels right.",
    ["WIZARD_OPT_TICKS"] = "Regen ticks",
    ["WIZARD_BLURB_TICKS"] = "Little floating numbers when you regen mana or health. Tick a box to see fake samples bounce around, and drag the anchor if you want them somewhere else.",
    ["WIZARD_OPT_COMBAT"] = "Combat helpers",
    ["WIZARD_BLURB_COMBAT"] = "Handy bits for a fight — procs, Animates, zombies, Life Force, and Undead stance nudges. Tick what you want, move things around, then Next when you're happy.",
    ["WIZARD_OPT_BUFFS"] = "Group buffs",
    ["WIZARD_BLURB_BUFFS"] = "In a group your buff bar gets messy fast. This stacks the same buff into one icon so you're not hunting through a wall of identical raises.",
    ["WIZARD_OPT_MINIONS"] = "Minion HUD",
    ["WIZARD_BLURB_MINIONS"] = "Keep an eye on your army — live HP bars you can place where you like, plus a bit of DPS info on spell tooltips if you want it.",
    ["WIZARD_OPT_PLATES"] = "Nameplates",
    ["WIZARD_BLURB_PLATES"] = "Prefer just names floating over heads? Or mute plates in busy capitals when FPS dips? Pick what helps.",
    ["WIZARD_OPT_MINIMAP"] = "Minimap button",
    ["WIZARD_BLURB_MINIMAP"] = "A little Leti button on the minimap so Hub and Setup are one click away. Handy if you don't want to remember /leti.",

    ["LOADED"] = "v%s loaded. Type /leti to open.",
    ["HELP_WELCOME"] = "First time here? A welcome popup will ask what you want from Leti — or type /leti welcome.",
    ["HELP_CHAT_HEADER"] = "Libellus Leti — player setup",
}

Mancer.LocaleModule.Register("enUS", L)
