-- Français (frFR)
local L = {
    ["MINIMAP_OPEN_HUB"] = "Ouvrir le Hub",
    ["MINIMAP_DISPLAY"] = "Paramètres",
    ["MINIMAP_LANGUAGE"] = "Langue",
    ["MINIMAP_HIDE"] = "Masquer le bouton de minicarte",
    ["MINIMAP_TIP_LEFT"] = "Clic gauche : ouvrir le Hub",
    ["MINIMAP_TIP_RIGHT"] = "Clic droit : menu",
    ["MINIMAP_TIP_DRAG"] = "Glisser : déplacer l’icône",

    ["LANGUAGE_TITLE"] = "Langue Libellus Leti",
    ["LANGUAGE_DESC"] = "Choisissez la langue des menus et options de Libellus Leti. Les noms de sorts et talents restent tels qu’Ascension les affiche.",
    ["LANGUAGE_SECTION"] = "Langue",
    ["LANGUAGE_APPLIED"] = "Langue mise à jour.",

    ["DISPLAY_TITLE"] = "Paramètres Libellus Leti",
    ["DISPLAY_DESC"] = "Rappels de stance, barres HUD, barres de nom et apparence.",
    ["SETTINGS_TAB_STANCE"] = "Rappels de stance",
    ["SETTINGS_TAB_DISPLAY"] = "Affichage",
    ["SETTINGS_TAB_NAMEPLATES"] = "Barres de nom",
    ["SETTINGS_TAB_APPEARANCE"] = "Apparence",
    ["SETTINGS_STANCE_TIP"] = "Choisir où les rappels de stance Undead peuvent apparaître.",
    ["SETTINGS_NAMEPLATES_TIP"] = "Masquer vie/ressource/incantation sur les barres de nom Ascension, garder le nom.",
    ["SECTION_WHERE"] = "Où",
    ["SECTION_DISPLAY"] = "Affichage",
    ["SECTION_BAR_TEXTURE"] = "Texture de barre",
    ["SECTION_MINION_HP_BAR"] = "Texture des sbires",
    ["SECTION_FONT"] = "Police",
    ["SECTION_FONT_SIZE"] = "Taille de police",
    ["SECTION_LAYOUT"] = "Disposition",

    ["WHERE_ALL"] = "Partout",
    ["WHERE_WORLD"] = "Monde ouvert",
    ["WHERE_RAID"] = "Raids",
    ["WHERE_DUNGEON"] = "Donjons",
    ["WHERE_ARENA"] = "Arènes",
    ["WHERE_BATTLEGROUND"] = "Champs de bataille",

    ["OPT_SHOW_MANA"] = "Afficher les ticks de mana",
    ["OPT_SHOW_HEALTH"] = "Afficher les ticks de vie",
    ["OPT_SHOW_REGEN_RATE"] = "Libellé du dernier tick de mana",
    ["OPT_REGEN_ONLY"] = "Filtre régénération seule",
    ["OPT_SHOW_MANA_BAR"] = "Afficher l’arc de mana",
    ["OPT_SHOW_HEALTH_BAR"] = "Afficher l’arc de vie",
    ["OPT_SHOW_RUNIC_BAR"] = "Afficher l’arc de puissance runique",
    ["OPT_SHOW_ANIMATE_BAR"] = "Afficher la barre Animate",
    ["OPT_CONSOLIDATE_BUFFS"] = "Empiler les buffs en double",
    ["OPT_SHOW_PROC_BAR"] = "Afficher la barre de procs",
    ["OPT_SHOW_ZOMBIE"] = "Afficher le compteur de zombies",
    ["OPT_SHOW_MINION_HP"] = "Afficher les barres de PV des sbires",
    ["SECTION_NAMEPLATES"] = "Barres de nom (noms seuls)",
    ["PLATE_ALL"] = "Tous",
    ["PLATE_GUARDIANS"] = "Gardiens",
    ["PLATE_PLAYERS"] = "Joueurs",
    ["PLATE_NPCS"] = "PNJ",
    ["PLATE_ENEMIES"] = "Ennemis",
    ["OPT_HIDE_FRIENDLY_PLATES"] = "Masquer les barres amicales",
    ["OPT_SHOW_MINIMAP"] = "Afficher le bouton de minicarte",
    ["OPT_MINION_TOOLTIPS"] = "DPS des sbires dans les infobulles",

    ["BTN_SHOW"] = "Afficher",
    ["BTN_HIDE"] = "Masquer",
    ["BTN_TEST_PREVIEW"] = "Tester l’aperçu",
    ["BTN_RESET_BARS"] = "Réinit. barres",

    ["HUB_TAB_COMBAT"] = "Combat",
    ["HUB_TAB_COMBAT_SUB"] = "Armée · LF · DPS",
    ["HUB_TAB_COMBAT_TIP"] = "Choix d’armée, Force vitale, DPS et ST contre AoE",
    ["HUB_TAB_MINIONS"] = "Sbires",
    ["HUB_TAB_MINIONS_SUB"] = "Fiche de gardien",
    ["HUB_TAB_MINIONS_TIP"] = "Fiche live des gardiens — stats et modèle",
    ["HUB_TAB_GUIDES"] = "Guides",
    ["HUB_TAB_GUIDES_SUB"] = "Stats · Papier · Buffs",
    ["HUB_TAB_GUIDES_TIP"] = "Plafonds de stats, DPS papier et choix de buffs",
    ["HUB_TAB_SETUP"] = "Réglages",
    ["HUB_TAB_SETUP_SUB"] = "Barres · Paramètres",
    ["HUB_TAB_SETUP_TIP"] = "Ouvrir les paramètres (stance, barres, noms, polices, disposition)",
    ["HUB_TAB_CREDITS"] = "Credits",
    ["HUB_TAB_CREDITS_SUB"] = "Remerciements",
    ["HUB_TAB_CREDITS_TIP"] = "Merci a tous ceux qui ont aide Libellus Leti",
    ["HUB_CREDITS_TITLE"] = "Remerciements",
    ["WIZARD_WELCOME_TITLE"] = "Bienvenue dans Libellus Leti",
    ["WIZARD_TITLE"] = "Que voulez-vous de Leti ?",
    ["WIZARD_SKIP"] = "Garder mes reglages",
    ["WIZARD_CONTINUE"] = "Continuer",
    ["WIZARD_BACK"] = "Retour",
    ["WIZARD_NEXT"] = "Suivant",
    ["WIZARD_FINISH"] = "Terminer",
    ["WIZARD_DONE"] = "Termine",

    ["LOADED"] = "v%s chargé. Tapez /leti pour ouvrir.",
    ["HELP_WELCOME"] = "Premiere fois ? Une fenetre vous demande ce que vous voulez de Leti — ou tapez /leti welcome.",
}

Mancer.LocaleModule.Register("frFR", L)
