-- Русский (ruRU)
local L = {
    ["MINIMAP_OPEN_HUB"] = "Открыть Hub",
    ["MINIMAP_DISPLAY"] = "Настройки",
    ["MINIMAP_LANGUAGE"] = "Язык",
    ["MINIMAP_HIDE"] = "Скрыть кнопку у миникарты",
    ["MINIMAP_TIP_LEFT"] = "ЛКМ: открыть Hub",
    ["MINIMAP_TIP_RIGHT"] = "ПКМ: меню",
    ["MINIMAP_TIP_DRAG"] = "Перетаскивание: сдвинуть значок",

    ["LANGUAGE_TITLE"] = "Язык Libellus Leti",
    ["LANGUAGE_DESC"] = "Выберите язык меню и настроек Libellus Leti. Названия заклинаний и талантов остаются как в Ascension.",
    ["LANGUAGE_SECTION"] = "Язык",
    ["LANGUAGE_APPLIED"] = "Язык обновлён.",

    ["DISPLAY_TITLE"] = "Настройки Libellus Leti",
    ["DISPLAY_DESC"] = "Подсказки стоек, HUD-полосы, неймплейты и оформление.",
    ["SETTINGS_TAB_STANCE"] = "Подсказки стоек",
    ["SETTINGS_TAB_DISPLAY"] = "Отображение",
    ["SETTINGS_TAB_NAMEPLATES"] = "Неймплейты",
    ["SETTINGS_TAB_APPEARANCE"] = "Оформление",
    ["SETTINGS_STANCE_TIP"] = "Где разрешены подсказки Undead-стойки.",
    ["SETTINGS_NAMEPLATES_TIP"] = "Скрыть полосы жизни/ресурса/каста на неймплейтах Ascension, оставить имя.",
    ["SECTION_WHERE"] = "Где",
    ["SECTION_DISPLAY"] = "Отображение",
    ["SECTION_BAR_TEXTURE"] = "Текстура полосы",
    ["SECTION_MINION_HP_BAR"] = "Текстура слуг",
    ["SECTION_FONT"] = "Шрифт",
    ["SECTION_FONT_SIZE"] = "Размер шрифта",
    ["SECTION_LAYOUT"] = "Расположение",

    ["WHERE_ALL"] = "Везде",
    ["WHERE_WORLD"] = "Открытый мир",
    ["WHERE_RAID"] = "Рейды",
    ["WHERE_DUNGEON"] = "Подземелья",
    ["WHERE_ARENA"] = "Арена",
    ["WHERE_BATTLEGROUND"] = "Поля боя",

    ["OPT_SHOW_MANA"] = "Показывать тики маны",
    ["OPT_SHOW_HEALTH"] = "Показывать тики здоровья",
    ["OPT_SHOW_REGEN_RATE"] = "Подпись последнего тика маны",
    ["OPT_REGEN_ONLY"] = "Только восстановление",
    ["OPT_SHOW_MANA_BAR"] = "Показывать дугу маны",
    ["OPT_SHOW_HEALTH_BAR"] = "Показывать дугу здоровья",
    ["OPT_SHOW_RUNIC_BAR"] = "Показывать дугу силы рун",
    ["OPT_SHOW_ANIMATE_BAR"] = "Показывать полосу Animate",
    ["OPT_CONSOLIDATE_BUFFS"] = "Складывать одинаковые бафы",
    ["OPT_SHOW_PROC_BAR"] = "Показывать полосу проков",
    ["OPT_SHOW_ZOMBIE"] = "Показывать счётчик зомби",
    ["OPT_SHOW_MINION_HP"] = "Показывать полосы здоровья слуг",
    ["SECTION_NAMEPLATES"] = "Индикаторы (только имена)",
    ["PLATE_ALL"] = "Все",
    ["PLATE_GUARDIANS"] = "Стражи",
    ["PLATE_PLAYERS"] = "Игроки",
    ["PLATE_NPCS"] = "NPC",
    ["PLATE_ENEMIES"] = "Враги",
    ["OPT_HIDE_FRIENDLY_PLATES"] = "Скрывать дружественные индикаторы",
    ["OPT_SHOW_MINIMAP"] = "Показывать кнопку у миникарты",
    ["OPT_MINION_TOOLTIPS"] = "ДПС слуг в подсказках заклинаний",

    ["BTN_SHOW"] = "Показать",
    ["BTN_HIDE"] = "Скрыть",
    ["BTN_TEST_PREVIEW"] = "Тест превью",
    ["BTN_RESET_BARS"] = "Сброс полос",

    ["HUB_TAB_COMBAT"] = "Бой",
    ["HUB_TAB_COMBAT_SUB"] = "Армия · СЖ · ДПС",
    ["HUB_TAB_COMBAT_TIP"] = "Выбор армии, Сила жизни, ДПС и СТ против AoE",
    ["HUB_TAB_MINIONS"] = "Слуги",
    ["HUB_TAB_MINIONS_SUB"] = "Лист стража",
    ["HUB_TAB_MINIONS_TIP"] = "Живой лист стража — характеристики и модель",
    ["HUB_TAB_GUIDES"] = "Гайды",
    ["HUB_TAB_GUIDES_SUB"] = "Статы · Бумага · Бафы",
    ["HUB_TAB_GUIDES_TIP"] = "Капы статов, бумажный ДПС и выбор бафов",
    ["HUB_TAB_SETUP"] = "Настройка",
    ["HUB_TAB_SETUP_SUB"] = "Полосы · Настройки",
    ["HUB_TAB_SETUP_TIP"] = "Открыть настройки (стойки, полосы, неймплейты, шрифты, расположение)",
    ["HUB_TAB_CREDITS"] = "Благодарности",
    ["HUB_TAB_CREDITS_SUB"] = "Спасибо",
    ["HUB_TAB_CREDITS_TIP"] = "Спасибо всем, кто помогал с Libellus Leti",
    ["HUB_CREDITS_TITLE"] = "Спасибо",
    ["WIZARD_WELCOME_TITLE"] = "Добро пожаловать в Libellus Leti",
    ["WIZARD_TITLE"] = "Что вам нужно от Leti?",
    ["WIZARD_SKIP"] = "Оставить настройки",
    ["WIZARD_CONTINUE"] = "Продолжить",
    ["WIZARD_BACK"] = "Назад",
    ["WIZARD_NEXT"] = "Далее",
    ["WIZARD_FINISH"] = "Готово",
    ["WIZARD_DONE"] = "Готово",

    ["LOADED"] = "v%s загружен. Введите /leti, чтобы открыть.",
    ["HELP_WELCOME"] = "Впервые здесь? Окно спросит, что вам нужно от Leti — или /leti welcome.",
}

Mancer.LocaleModule.Register("ruRU", L)
-- Catalogs are all registered after this file; apply default so early UI lookups resolve.
if Mancer.LocaleModule.Apply then
    Mancer.LocaleModule.Apply()
end
