"""
derive_tooltip_holes.py - the description-hole id list, derived + baked for the harness.

Scans the inventory captures (Weak Auras/ability_inventory/out/<CLASS>.json) for
abilities whose text is NULL or carries an unresolved $-variable, filters to
custom-range spell ids (>= 500000 - stock-id nulls are benign scrape artifacts
of stock passives), dedupes by id, and emits:

  addons/maps/tooltip_holes.json        the tracked derivation (id -> name/kind/classes)
  addons/COA_DevDump/payload_tooltipids.lua   the baked list the `tooltip` task
                                              uses via `/coadump r tooltip holes`

Deterministic; re-run after any inventory refresh. The in-game render is the
ARBITER for every id here (accept-empty only on the game's verdict).
"""
import glob
import json
from datetime import datetime
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
INV = REPO / "Weak Auras" / "ability_inventory" / "out"
MAPS = REPO / "addons" / "maps"
ADDON = REPO / "addons" / "COA_DevDump"


def main():
    byid = {}
    for f in sorted(glob.glob(str(INV / "[A-Z]*.json"))):
        cls = Path(f).stem
        d = json.loads(Path(f).read_text(encoding="utf-8"))
        entries = d.get("abilities", d if isinstance(d, list) else [])
        if isinstance(entries, dict):
            entries = list(entries.values())
        for e in entries:
            if not isinstance(e, dict):
                continue
            txt = e.get("text") or e.get("description")
            kind = "NULL" if not txt else ("VAR" if "$" in txt else None)
            if kind is None:
                continue
            for sid in (e.get("spellIds") or []):
                if sid >= 500000:
                    row = byid.setdefault(sid, {"name": e.get("name"), "kind": kind, "classes": []})
                    if cls not in row["classes"]:
                        row["classes"].append(cls)

    ids = sorted(byid)
    with open(MAPS / "tooltip_holes.json", "w", encoding="utf-8") as f:
        json.dump({
            "derived_at": datetime.now().isoformat(timespec="seconds"),
            "deriver": "addons/tools/derive_tooltip_holes.py",
            "grain": "unique custom-range (>=500000) ability ids whose inventory text is NULL "
                     "or carries an unresolved $-variable; the in-game render is the arbiter",
            "count": len(ids),
            "holes": {str(sid): byid[sid] for sid in ids},
        }, f, indent=1, ensure_ascii=False)

    lua_ids = ",".join(str(i) for i in ids)
    (ADDON / "payload_tooltipids.lua").write_text(
        "-- GENERATED by addons/tools/derive_tooltip_holes.py - DO NOT EDIT, regenerate.\n"
        f"-- {len(ids)} unique custom-range description holes; derivation: addons/maps/tooltip_holes.json\n"
        f"-- derived: {datetime.now().isoformat(timespec='seconds')}\n"
        "local ADDON, D = ...\n"
        "D.payloads = D.payloads or {}\n"
        "D.payloads[\"tooltip_holes\"] = { " + lua_ids + " }\n",
        encoding="utf-8")

    print(f"{len(ids)} holes -> maps/tooltip_holes.json + COA_DevDump/payload_tooltipids.lua")


if __name__ == "__main__":
    main()
