# -*- coding: utf-8 -*-
r"""read_framexml_lua.py - extract the client's own FrameXML/SharedXML Lua from the MPQ
chain so the harness can RUN it instead of stubbing it.

    py addons\tools\read_framexml_lua.py
    -> addons\staging\framexml_lua\...          (gitignored, regenerated)
    -> addons\staging\framexml_lua_manifest.txt (load order, from FrameXML.toc)

★★★ WHY (A10.1c, bench U6 answer (c)). `AceConfigDialog:Open` reaches TabGroup and calls
`PanelTemplates_TabResize` — a Blizzard FrameXML FUNCTION, not a template. We could write
our own; ours would be right until Blizzard's arithmetic and ours disagree, with nothing
to notice when they do. `patch-B.MPQ` carries 823 `.lua` files including
`Interface\FrameXML\UIPanelTemplates.lua`, so the real one is simply readable.

★ THE LOAD ORDER IS THE CLIENT'S OWN. `Interface\FrameXML\FrameXML.toc` lists what the UI
loads and in what order — 344 entries. We do not invent an order; we read theirs, and the
`..\SharedXML\` entries in it are why a scan of `Interface\FrameXML\` alone came up short
(§351).

⚠ READ-ONLY ON THE CLIENT. Nothing is ever written under F:\games. Output is Blizzard's
content: it lives in gitignored staging and is REGENERATED, never carried or edited.
"""

import io
import os
import re
import sys

sys.stdout.reconfigure(encoding="utf-8")

from mpyq import MPQArchive

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DATA = r"F:\games\Ascension_wow\resources\ascension-live\Data"
OUT = os.path.join(REPO, "addons", "staging", "framexml_lua")
MANIFEST = os.path.join(REPO, "addons", "staging", "framexml_lua_manifest.txt")
TOC = r"Interface\FrameXML\FrameXML.toc"


def archives():
    for n in sorted(os.listdir(DATA)):
        if n.lower().endswith(".mpq"):
            yield n, os.path.join(DATA, n)


def open_all():
    out = []
    for n, p in archives():
        try:
            out.append((n, MPQArchive(p, listfile=False)))
        except Exception:
            pass                       # unreadable archives are counted by the caller
    return out


def read_any(handles, path):
    """★ BY NAME, not by listfile. An MPQ hashes filenames, so a file is readable from an
    archive whose listfile is missing — the mistake that made me report four archives as
    carrying no FrameXML when the truth was that I could not look (§351)."""
    for n, a in handles:
        try:
            blob = a.read_file(path)
        except Exception:
            blob = None
        if blob:
            return n, blob
    return None, None


def toc_entries(text):
    """`FrameXML.toc` order, `..\\Foo\\` resolved against Interface\\."""
    out = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if not line.lower().endswith(".lua"):
            continue                   # xml is read by read_templates.py, not here
        p = line.replace("/", "\\")
        if p.startswith("..\\"):
            p = "Interface\\" + p[3:]
        else:
            p = "Interface\\FrameXML\\" + p
        out.append(p)
    return out


def main():
    handles = open_all()
    total = sum(1 for _ in archives())
    print("  %d of %d archive(s) opened" % (len(handles), total))

    src, blob = read_any(handles, TOC)
    if not blob:
        print("  FrameXML.toc not readable in any archive")
        return 1
    entries = toc_entries(blob.decode("utf-8", "replace"))
    print("  %s -> FrameXML.toc, %d lua entries in load order" % (src, len(entries)))

    if not os.path.isdir(OUT):
        os.makedirs(OUT)

    got, missing, lines = 0, [], []
    for p in entries:
        arch, data = read_any(handles, p)
        if not data:
            missing.append(p)
            continue
        dest = os.path.join(OUT, p.replace("\\", os.sep))
        d = os.path.dirname(dest)
        if not os.path.isdir(d):
            os.makedirs(d)
        io.open(dest, "wb").write(data)
        lines.append(p)
        got += 1

    io.open(MANIFEST, "w", encoding="utf-8", newline="\n").write(
        "# GENERATED by addons/tools/read_framexml_lua.py - the CLIENT'S OWN load order,\n"
        "# read from Interface\\FrameXML\\FrameXML.toc. One path per line, in order.\n"
        + "\n".join(lines) + "\n")

    print("  extracted %d / %d  -> addons/staging/framexml_lua/" % (got, len(entries)))
    # ⚠ MISSING IS NAMED, NEVER COUNTED ONLY. A file the toc asks for and the chain does
    # not hold is a hole the harness will meet at load time; it should meet it here first.
    if missing:
        print("  %d listed by the toc and NOT in the chain:" % len(missing))
        for m in missing[:12]:
            print("    ? %s" % m)
        if len(missing) > 12:
            print("    ... and %d more" % (len(missing) - 12))
    return 0


if __name__ == "__main__":
    sys.exit(main())
