"""
wrap_payload.py - materialize a cross-lane Lua payload into the COA_DevDump harness.

A payload (e.g. macros/probe/probe_core.lua) is a self-contained chunk ending in
`return <fn>`, owned by another bench and NEVER edited here. WoW Lua has no file
I/O, so a task can't load it at runtime - this tool wraps it VERBATIM in an IIFE
inside a generated addon file, exposing it as D.payloads[<name>] with sha256
provenance riding along in D.payloadMeta[<name>].

Usage:
    py addons\\tools\\wrap_payload.py macros\\probe\\probe_core.lua macros

Regenerate whenever the source payload changes; the generated file says so on
line 1 and carries the source sha - a stale wrapper is detectable, never silent.
"""
import hashlib
import sys
from datetime import datetime
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
ADDON = REPO / "addons" / "COA_DevDump"


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(2)
    src = REPO / sys.argv[1]
    name = sys.argv[2]
    body = src.read_text(encoding="utf-8")
    sha = hashlib.sha256(body.encode("utf-8")).hexdigest()

    out = ADDON / f"payload_{name}.lua"
    rel = src.relative_to(REPO)
    wrapper = (
        f"-- GENERATED by addons/tools/wrap_payload.py from {rel} - DO NOT EDIT, regenerate.\n"
        f"-- source sha256: {sha}\n"
        f"-- wrapped: {datetime.now().isoformat(timespec='seconds')}\n"
        f"-- The payload below is VERBATIM (the owning bench's file); only this header and\n"
        f"-- the enclosing IIFE/namespace lines are the harness's.\n"
        f"local ADDON, D = ...\n"
        f"D.payloads = D.payloads or {{}}\n"
        f"D.payloadMeta = D.payloadMeta or {{}}\n"
        f'D.payloadMeta["{name}"] = {{ src = "{rel.as_posix()}", sha256 = "{sha}" }}\n'
        f'D.payloads["{name}"] = (function()\n'
        f"{body}\n"
        f"end)()\n"
    )
    out.write_text(wrapper, encoding="utf-8")
    print(f"wrapped {rel} -> {out.relative_to(REPO)} (sha {sha[:16]}...)")


if __name__ == "__main__":
    main()
